server:
  port: 8080
  servlet:
    context-path: /mail
    session:
      timeout: 1800

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mailbox?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

  freemarker:
    template-loader-path: classpath:/templates
    # 关闭缓存，及时刷新，上线生产环境需要修改为true
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    suffix: .ftl
    settings:
      template_update_delay: 0

  redis:
    database: 0
    host: localhost
    password:
    port: 6379
    timeout: 2000
    maxActive: 100000
    maxIdle: 100000
    minIdle: 0
    maxWait: 1000
    shutdownTimeout: 100
    serializer: org.springframework.data.redis.serializer.Jackson2JsonRedisSerializer

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 0
      # 删除后
      logic-delete-value: 1

email:
  storage:
    path: C:/Users/EDZ/Desktop/email/